# Generated by Django 2.2.7 on 2019-11-12 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrients', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=10)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.Food')),
            ],
        ),
    ]
